name: Our Holy Conception
favicon: null
layout_spectrum: 1
typography_spectrum: 0.97282
title: 'Our Holy Conception: Marriage as your path to holiness'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#243522'
    - '#b22b4b'
    - '#808080'
    - '#71cff2'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
