name: Our Holy Conception
favicon: null
layout_spectrum: 1
typography_spectrum: 0.97282
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5dbde7'
    - '#0b0c06'
    - '#d0bda9'
    - '#884f3e'
    - '#005ac5'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
