typography_spectrum: 0.47437606868334115
color:
  brandColors:
    - '#5DBDE7'
    - '#0A0B05'
    - '#CFBDA9'
    - '#884F3E'
    - '#0051BD'
  brandStrength: 0.17503351205959916
  lightness: 0.7830721330828965
  saturation: 0.724446028470993
  rhythmicContrast: 0.8961822674609721
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25151837477460504
analytics:
  google: UA-3182397-9
  facebook: null
  twitter: null
author:
  name: Deacon Patrick Jones
  email: lamontglen@mac.com
  url: www.OurHolyConception.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2638b5c6-9458-4f71-8e09-aca8c6c206e0.png
name: Our Holy Conception
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 88036f4f-b0dc-4792-b835-74637294d6af
    type: content
  - name: Give
    id: 731d6168-a625-4f42-8b6b-1ea047d5515c
    type: content
  - name: Trinity Sword Prayer
    id: 85ab686a-09b8-48a6-b582-ba3bc8103b25
    type: content
  - name: Save Your Marriage!
    id: db1233ae-aa00-4278-8858-34874d6b4b0e
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2416bd62-4395-414c-be86-478e77a48faf.jpg
title: Our Holy Conception
description: Marriage as your path to holiness
purpose: []
