name: Our Holy Conception
favicon: null
layout_spectrum: 0.49818
typography_spectrum: 0.19107
title: Our Holy Conception
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-3182397-9
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5dbde7'
    - '#0b0c06'
    - '#d0bda9'
    - '#884f3e'
    - '#005ac5'
  brandStrength: 0.5625
  lightness: 0.5
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
